// Code generated by "stringer -type HttpCode -linecomment"; DO NOT EDIT.

package merrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HttpOK-200]
	_ = x[Http404-403]
}

const (
	_HttpCode_name_0 = "正常"
	_HttpCode_name_1 = "无权限"
)

func (i HttpCode) String() string {
	switch {
	case i == 200:
		return _HttpCode_name_0
	case i == 403:
		return _HttpCode_name_1
	default:
		return "HttpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
